version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    network_mode: 'host'

volumes:
  postgres-db:
    driver: local